Repository yirumuim/MovieOntology, pull requests merged in 2019-08, with the labels that each got.

#3 Add Issue&PR template
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: enhancement

#5 Add gitignore
  .gitignore
Labels: enhancement

#6 Add creat-react-app
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.js
  src/App.test.js
  src/index.css
  src/index.js
  src/logo.svg
  src/serviceWorker.js
  yarn.lock
Labels: enhancement

#16 Modifiied jinhyeok name
  README.md
Labels: Review Need, documentation

#18 Readme에 정균휘 이름추가
  README.md
Labels: Review Need, documentation

#17 readme에 신승혁이름 추가 & eslintrc에 window 설정 추가
  .eslintrc
  README.md
Labels: Review Need, documentation

#26 폴더 트리 정리 및 ExtraContents 추가
  .eslintrc
  src/App.jsx
  src/components/ExtraContentsWrapper/ExtraContentsWrapper.css
  src/components/ExtraContentsWrapper/ExtraContentsWrapper.js
  src/components/Header/Header.js
  src/components/Item/Item.css
  src/components/Item/Item.js
  src/components/ItemList/ItemList.css
  src/components/ItemList/ItemList.js
  src/components/Scroll/Scroll.js
  src/components/index.js
  src/containers/ApplicationContainer/ApplicationContainer.jsx
  src/containers/ContentContainer/ContentContainer.jsx
  src/containers/ExtraContentsContainer/ExtraContentsContainer.jsx
  src/containers/index.js
  src/movie_image.jpg
Labels: ProtoType, Review Need, enhancement
